<x-datatable
    :searchbarPlaceholder="$searchbarPlaceholder"
    :filters="$filters"
    :perPageOptions="$perPageOptions"
    :table="$table"
    :data="$data"
    :newResourceLinkPermission="$newResourceLinkPermission"
    :newResourceLinkRouteName="$newResourceLinkRouteName"
    :newResourceLinkLabel="$newResourceLinkLabel"
/>
