<x-datatable
    :searchbarPlaceholder="$searchbarPlaceholder"
    :filters="$filters"
    :customFilters="$customFilters"
    :perPageOptions="$perPageOptions"
    :headers="$headers"
    :noResultsMessage="$noResultsMessage"
    :customNoResultsMessage="$customNoResultsMessage"
    :data="$data"
    :newResourceLinkPermission="$newResourceLinkPermission"
    :newResourceLinkRouteName="$newResourceLinkRouteName"
    :newResourceLinkLabel="$newResourceLinkLabel"
/>
